export const SERVICES_DATA = [
  {
    category: "PELUQUERÍA",
    title: "Corte & Peinado",
    price: "Desde $5.500",
    time: "60 MIN",
    desc: "Cortes de autor adaptados a tu visagismo. Incluye peinado social y lavado nutritivo profundo.",
    items: [
      "Corte Dama/Caballero",
      "Peinados de Gala",
      "Lavado con Masaje",
      "Brushing Élite",
    ],
  },
  {
    category: "SALUD CAPILAR",
    title: "Tratamientos Pro",
    price: "Desde $9.500",
    time: "120 MIN",
    desc: "Protocolos intensivos para reconstruir la fibra capilar y devolver el brillo natural.",
    items: [
      "Botox Capilar",
      "Shock de Queratina",
      "Hidratación Molecular",
      "Nutrición Iónica",
    ],
    premium: true,
  },
  {
    category: "COLOR & FORMA",
    title: "Tintes & Alisados",
    price: "Desde $12.000",
    time: "180 MIN",
    desc: "Colorimetría avanzada y cambios estructurales que respetan la salud de tu cabello.",
    items: [
      "Tintes sin Amoníaco",
      "Alisado Permanente",
      "Permanentes/Ondas",
      "Balayage Élite",
    ],
    premium: true,
  },
  {
    category: "MANOS Y PIES",
    title: "Manicura & Pedicura",
    price: "Desde $3.500",
    time: "90 MIN",
    desc: "Estética profunda de uñas con esmaltado semipermanente y tratamientos de spa.",
    items: [
      "Manicura Rusa",
      "Pedicura Profunda",
      "Nail Art Custom",
      "Exfoliación con Parafina",
    ],
  },
  {
    category: "ESTÉTICA FACIAL",
    title: "Maquillaje & Depi",
    price: "Desde $2.800",
    time: "45 MIN",
    desc: "Servicios complementarios para armonizar tu rostro y resaltar tu belleza facial.",
    items: [
      "Maquillaje Social/HD",
      "Depilación Facial",
      "Perfilado de Cejas",
      "Higiene Facial",
    ],
  },
];
